version: "3.9"
services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    ports:
      - 22222:8080
    environment:
      DOZZLE_AUTH_PROVIDER: simple
    restart: unless-stopped
